/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminAtuacaoRouteImport } from './routes/admin._admin.atuacao'
import { Route as AdminAdminClientesRouteImport } from './routes/admin._admin.clientes'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/admin._admin.configuracoes'
import { Route as AdminAdminContatosRouteImport } from './routes/admin._admin.contatos'
import { Route as AdminAdminDepoimentosRouteImport } from './routes/admin._admin.depoimentos'
import { Route as AdminAdminFormularioRouteImport } from './routes/admin._admin.formulario'
import { Route as AdminAdminSeoRouteImport } from './routes/admin._admin.seo'
import { Route as AdminAdminServicosRouteImport } from './routes/admin._admin.servicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAtuacaoRoute = AdminAdminAtuacaoRouteImport.update({
  id: '/atuacao',
  path: '/atuacao',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientesRoute = AdminAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminContatosRoute = AdminAdminContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminDepoimentosRoute = AdminAdminDepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFormularioRoute = AdminAdminFormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSeoRoute = AdminAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminServicosRoute = AdminAdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/atuacao': typeof AdminAdminAtuacaoRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/contatos': typeof AdminAdminContatosRoute
  '/admin/depoimentos': typeof AdminAdminDepoimentosRoute
  '/admin/formulario': typeof AdminAdminFormularioRoute
  '/admin/seo': typeof AdminAdminSeoRoute
  '/admin/servicos': typeof AdminAdminServicosRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/atuacao': typeof AdminAdminAtuacaoRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/contatos': typeof AdminAdminContatosRoute
  '/admin/depoimentos': typeof AdminAdminDepoimentosRoute
  '/admin/formulario': typeof AdminAdminFormularioRoute
  '/admin/seo': typeof AdminAdminSeoRoute
  '/admin/servicos': typeof AdminAdminServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_admin/atuacao': typeof AdminAdminAtuacaoRoute
  '/admin/_admin/clientes': typeof AdminAdminClientesRoute
  '/admin/_admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/_admin/contatos': typeof AdminAdminContatosRoute
  '/admin/_admin/depoimentos': typeof AdminAdminDepoimentosRoute
  '/admin/_admin/formulario': typeof AdminAdminFormularioRoute
  '/admin/_admin/seo': typeof AdminAdminSeoRoute
  '/admin/_admin/servicos': typeof AdminAdminServicosRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clientes'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/login'
    | '/admin/atuacao'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/depoimentos'
    | '/admin/formulario'
    | '/admin/seo'
    | '/admin/servicos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/clientes'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/login'
    | '/admin/atuacao'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/depoimentos'
    | '/admin/formulario'
    | '/admin/seo'
    | '/admin/servicos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clientes'
    | '/contato'
    | '/servicos'
    | '/sobre'
    | '/admin/_admin'
    | '/admin/login'
    | '/admin/_admin/atuacao'
    | '/admin/_admin/clientes'
    | '/admin/_admin/configuracoes'
    | '/admin/_admin/contatos'
    | '/admin/_admin/depoimentos'
    | '/admin/_admin/formulario'
    | '/admin/_admin/seo'
    | '/admin/_admin/servicos'
    | '/admin/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/atuacao': {
      id: '/admin/_admin/atuacao'
      path: '/atuacao'
      fullPath: '/admin/atuacao'
      preLoaderRoute: typeof AdminAdminAtuacaoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/clientes': {
      id: '/admin/_admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminAdminClientesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/configuracoes': {
      id: '/admin/_admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/contatos': {
      id: '/admin/_admin/contatos'
      path: '/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminAdminContatosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/depoimentos': {
      id: '/admin/_admin/depoimentos'
      path: '/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AdminAdminDepoimentosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/formulario': {
      id: '/admin/_admin/formulario'
      path: '/formulario'
      fullPath: '/admin/formulario'
      preLoaderRoute: typeof AdminAdminFormularioRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/seo': {
      id: '/admin/_admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminAdminSeoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/servicos': {
      id: '/admin/_admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminAdminServicosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAtuacaoRoute: typeof AdminAdminAtuacaoRoute
  AdminAdminClientesRoute: typeof AdminAdminClientesRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminContatosRoute: typeof AdminAdminContatosRoute
  AdminAdminDepoimentosRoute: typeof AdminAdminDepoimentosRoute
  AdminAdminFormularioRoute: typeof AdminAdminFormularioRoute
  AdminAdminSeoRoute: typeof AdminAdminSeoRoute
  AdminAdminServicosRoute: typeof AdminAdminServicosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAtuacaoRoute: AdminAdminAtuacaoRoute,
  AdminAdminClientesRoute: AdminAdminClientesRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminContatosRoute: AdminAdminContatosRoute,
  AdminAdminDepoimentosRoute: AdminAdminDepoimentosRoute,
  AdminAdminFormularioRoute: AdminAdminFormularioRoute,
  AdminAdminSeoRoute: AdminAdminSeoRoute,
  AdminAdminServicosRoute: AdminAdminServicosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientesRoute: ClientesRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
